"""trading_engine

Revision ID: d67ca5199ded
Revises: f8f12c721cd1
Create Date: 2026-08-10 15:13:25.450573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd67ca5199ded'
down_revision: Union[str, None] = 'f8f12c721cd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create the new Enum type first
    order_type = sa.Enum('MARKET', 'LIMIT', 'STOP_LOSS', name='ordertype')
    order_type.create(op.get_bind(), checkfirst=True)
    
    # Add new values to existing OrderStatus enum
    # This must be done outside a transaction block if using older Postgres, but we'll try raw SQL
    with op.get_context().autocommit_block():
        try:
            op.execute("ALTER TYPE orderstatus ADD VALUE 'TRIGGERED'")
            op.execute("ALTER TYPE orderstatus ADD VALUE 'EXECUTING'")
        except Exception:
            # Might already exist or dialect doesn't support it
            pass

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_type', order_type, server_default='MARKET', nullable=False))
        batch_op.add_column(sa.Column('limit_price', sa.DECIMAL(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('stop_price', sa.DECIMAL(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('triggered_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('executed_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
        batch_op.alter_column('total_amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True)
        batch_op.create_index('idx_status_symbol', ['status', 'symbol'], unique=False)
        batch_op.create_index('idx_status_symbol_side', ['status', 'symbol', 'side'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_order_type'), ['order_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_order_type'))
        batch_op.drop_index('idx_status_symbol_side')
        batch_op.drop_index('idx_status_symbol')
        batch_op.alter_column('total_amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
        batch_op.drop_column('executed_at')
        batch_op.drop_column('triggered_at')
        batch_op.drop_column('stop_price')
        batch_op.drop_column('limit_price')
        batch_op.drop_column('order_type')
        
    # Drop the enum type
    op.execute("DROP TYPE ordertype")
